// <auto-generated />
using InternsManager.DAL.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternsManager.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220601152205_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InternsManager.DAL.Entities.Intern", b =>
                {
                    b.Property<int>("IdIntern")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIntern"), 1L, 1);

                    b.Property<int>("IdInternship")
                        .HasColumnType("int");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("VacationDays")
                        .HasColumnType("int");

                    b.HasKey("IdIntern");

                    b.ToTable("Interns");

                    b.HasData(
                        new
                        {
                            IdIntern = 1,
                            IdInternship = 1,
                            IdPerson = 1,
                            VacationDays = 28
                        },
                        new
                        {
                            IdIntern = 2,
                            IdInternship = 2,
                            IdPerson = 2,
                            VacationDays = 26
                        },
                        new
                        {
                            IdIntern = 3,
                            IdInternship = 3,
                            IdPerson = 3,
                            VacationDays = 28
                        },
                        new
                        {
                            IdIntern = 4,
                            IdInternship = 4,
                            IdPerson = 4,
                            VacationDays = 28
                        },
                        new
                        {
                            IdIntern = 5,
                            IdInternship = 4,
                            IdPerson = 5,
                            VacationDays = 28
                        },
                        new
                        {
                            IdIntern = 6,
                            IdInternship = 3,
                            IdPerson = 6,
                            VacationDays = 28
                        });
                });

            modelBuilder.Entity("InternsManager.DAL.Entities.Internship", b =>
                {
                    b.Property<int>("IdInternship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInternship"), 1L, 1);

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryBRUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInternship");

                    b.ToTable("Internships");

                    b.HasData(
                        new
                        {
                            IdInternship = 1,
                            EndDate = "1.07.2022",
                            Name = "DiscoverIT",
                            Position = "Software Engineer Intern",
                            SalaryBRUT = "1500 Lei",
                            StartDate = "1.06.2022"
                        },
                        new
                        {
                            IdInternship = 2,
                            EndDate = "22.08.2022",
                            Name = "QA Internship",
                            Position = "QA Intern",
                            SalaryBRUT = "1750 Lei",
                            StartDate = "23.05.2022"
                        },
                        new
                        {
                            IdInternship = 3,
                            EndDate = "14.09.2022",
                            Name = "TriangleXperience",
                            Position = "Web Develover Intern",
                            SalaryBRUT = "1500 Lei",
                            StartDate = "15.06.2022"
                        },
                        new
                        {
                            IdInternship = 4,
                            EndDate = "19.09.2022",
                            Name = "TetraTech",
                            Position = "Junior Programmer Intern",
                            SalaryBRUT = "1620 Lei",
                            StartDate = "20.06.2022"
                        });
                });

            modelBuilder.Entity("InternsManager.DAL.Entities.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"), 1L, 1);

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            DateOfBirth = "4.05.2002",
                            Gender = "M",
                            Name = "Alexandru Ivanoff",
                            PicPath = "https://cdn.pixabay.com/photo/2017/11/26/00/30/teen-2977908_960_720.jpg"
                        },
                        new
                        {
                            IdPerson = 2,
                            DateOfBirth = "12.11.1990",
                            Gender = "F",
                            Name = "Irina Defta",
                            PicPath = "https://cdn.pixabay.com/photo/2015/03/03/18/58/woman-657753_1280.jpg"
                        },
                        new
                        {
                            IdPerson = 3,
                            DateOfBirth = "23.02.2002",
                            Gender = "M",
                            Name = "Florian-Andrei Barbu",
                            PicPath = "https://cdn.pixabay.com/photo/2016/03/04/21/24/portrait-1236732_1280.jpg"
                        },
                        new
                        {
                            IdPerson = 4,
                            DateOfBirth = "02.04.2002",
                            Gender = "M",
                            Name = "Augustin Petrica",
                            PicPath = "https://cdn.pixabay.com/photo/2020/03/01/22/43/young-4894362_1280.jpg"
                        },
                        new
                        {
                            IdPerson = 5,
                            DateOfBirth = "05.09.2000",
                            Gender = "F",
                            Name = "Oana Cretu",
                            PicPath = "https://cdn.pixabay.com/photo/2018/08/03/16/14/young-girl-3582188_1280.jpg"
                        },
                        new
                        {
                            IdPerson = 6,
                            DateOfBirth = "29.11.20001",
                            Gender = "F",
                            Name = "Ema Drobescu",
                            PicPath = "https://cdn.pixabay.com/photo/2017/08/28/16/29/portrait-2690308_1280.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
